### ISSUE TITLE
[BUG] SRT crashes upon attaching to game process.

### ISSUE THREAD

**Issue by LeafBucket** [Squirrelies/RE2REmakeSRT#12] opened 2019-02-14 17:27 UTC
**Computer Information:**
 - Windows 10 ver 1803
 - Program Version 1.1.8.3
 - Game Version: Unsure

**Describe the bug**
SRT does not start, I get error popup

**Steps to Reproduce**
I get the normal "The program will start once re2.exe is detected as running..." window
when I start the game I get the error message and the srt fails to start.

![capture](https://user-images.githubusercontent.com/20327434/52805105-25d55680-3086-11e9-9837-e232fafcb405.PNG)

**Comment by Squirrelies** [comment] 2019-02-14 18:33
I know where in the code it is happening but not why since it doesn't happen on my machine. Would you be willing to run a test build and help me track this down?

**Comment by LeafBucket** [comment] 2019-02-14 19:30
Yupp

**Comment by Squirrelies** [comment] 2019-02-14 19:34
Ok I'll make a test build shortly with extra try/catch statements and debug info to see what parameter is invalid.

**Comment by LeafBucket** [comment] 2019-02-14 19:35
I restarted my computer and tried to run as administrator again and I got this error now.
![capture](https://user-images.githubusercontent.com/20327434/52812544-fe878500-3097-11e9-8def-cf5282a77725.PNG)

**Comment by jorgebonafe** [comment] 2019-02-14 20:06
I can confirm the same error is happening for me, both running SRT before the game (it crashes when the game opens), and after the game is running, same version, 1.1.8.3.

![image](https://user-images.githubusercontent.com/1023068/52814307-f5d88400-3082-11e9-825b-342cf741f372.png)

**Comment by Squirrelies** [comment] 2019-02-14 22:49
http://dudley.gg/squirrelies/re2/RE2REmakeSRT-1184-Beta-Signed-Debug.7z

This won't fix the issue but should give me more info to find the problem. Can you get me the error message from this build?

**Comment by jorgebonafe** [comment] 2019-02-14 22:52
This is the new error message:

![image](https://user-images.githubusercontent.com/1023068/52822976-7d7dbd00-309a-11e9-888d-352989e7b60c.png)

**Comment by Squirrelies** [comment] 2019-02-14 22:59
By any chance is your Scaling Factor set to 75 instead of 0.75?

Regedit:
HKEY_CURRENT_USER\Software\RE2REmakeSRT\ScalingFactor

**Comment by LeafBucket** [comment] 2019-02-14 23:10
![capture](https://user-images.githubusercontent.com/20327434/52823661-0eae5d00-30b6-11e9-95e0-315fbbefc8e1.PNG)
I am getting a slightly different error message and I checked my Regedit and the scaling factor option was not there!

**Comment by jorgebonafe** [comment] 2019-02-14 23:21
Ok, I tried what LeafBucket tried, rebooted and ran it on Admin mode, and got a different message:

![image](https://user-images.githubusercontent.com/1023068/52824009-2548ba00-309e-11e9-8816-a2f498f21bfd.png)

Also, my registry on RE2REmakeSRT has no values at all:

![image](https://user-images.githubusercontent.com/1023068/52824055-47423c80-309e-11e9-9f26-aab3b6004b15.png)

Sorry about the portuguese on the error message, I don't know how to change that... It says: "Only a portion of a request ReadProcessMemory or WRiteProcessMemory has concluded in ..."

**Comment by Squirrelies** [comment] 2019-02-14 23:25
Yeah we're dealing with two different issues at the same time.

The ReadProcessMemory error is a different issue. We should open a separate bug for that one.

One moment while I prepare another build. I want to see what Program.programSpecialOptions.ScalingFactor returns.

**Comment by Squirrelies** [comment] 2019-02-14 23:27
http://dudley.gg/squirrelies/re2/RE2REmakeSRT-1184-Beta-Signed-Debug-2.7z

**Comment by LeafBucket** [comment] 2019-02-14 23:29
![capture](https://user-images.githubusercontent.com/20327434/52824410-b167db00-30b8-11e9-88e1-c9db188311d8.PNG)
Error I got after downloading your latest link!

**Comment by Squirrelies** [comment] 2019-02-14 23:41
Ok, that is the other error again. Let me finish up these P/Invoke calls since some people suggest that ERROR_PARTIAL_COPY (299) which triggers that Win32Exception can be caused by weird WoW64 behavior.

With EnumProcessModulesEx I can explicitly tell it to only give me 64-bit modules and also just avoid all of the extra stuff .NET is doing in the background when I call Process.BaseAddress and Process.MainModule.FullPath.

I should have a new build shortly.

**Comment by Squirrelies** [comment] 2019-02-14 23:44
http://dudley.gg/squirrelies/re2/RE2REmakeSRT-1184-Beta-Signed-Debug-3.7z

P.s. I really appreciate your help with this since I am unable to reproduce this on my machine. I am not sure what is different between our environments but I am curious what the cause is so we can finally solve this. :) <3

**Comment by Squirrelies** [comment] 2019-02-14 23:48
If the Win32Exception disappears and the other error reappears (ArgumentException), that is a good sign. it means we may have fixed that other error.

**Comment by LeafBucket** [comment] 2019-02-14 23:49
![capture](https://user-images.githubusercontent.com/20327434/52825024-71562780-30bb-11e9-9012-23ba5addb531.PNG)
My pleasure :). This is the new error I am getting

**Comment by Squirrelies** [comment] 2019-02-14 23:50
Excellent, so for some reason the scaling factor is defaulting or being set to 0 which causes the image to try to resize to 0x0 which .NET is telling me is not possible.

I'll search in the settings code and see if I can find out why it is being dumb. I may just add code for now that says the value must be greater than 0 and less than or equal to 4 (400%)

**Comment by LeafBucket** [comment] 2019-02-14 23:53
Sounds good!

**Comment by Squirrelies** [comment] 2019-02-15 00:01
http://dudley.gg/squirrelies/re2/RE2REmakeSRT-1184-Beta-Signed-Debug-4.7z

This code has checks for the scalingFactor and will set it to 0.75 if its less than or equal to 0 or greater than 4. It also has error handling on the registry reading code. See if this helps.

**Comment by LeafBucket** [comment] 2019-02-15 00:03
That did it 👍 Thanks for the help!

**Comment by Squirrelies** [comment] 2019-02-15 00:03
Awesome, thanks for all of your help on this. This has been a nagging issue for a little while now. :)

**Closed by Squirrelies** 2019-02-15 00:03 UTC
Labels: Bug, Unable To Reproduce

**Comment by LeafBucket** [comment] 2019-02-15 00:07
My pleasure. Great work on the program!

**Comment by Squirrelies** [comment] 2019-02-15 00:17
http://dudley.gg/squirrelies/re2/RE2REmakeSRT-1184-Beta-Signed-Release.7z

Release build with the fix.
